### ISSUE TITLE
Channel Members 'me' property not set

### ISSUE THREAD

**Issue by callmephilip** [leggetter/pusher-test-stub#1]
Based on what I've seen, the 'me' property is not set for Channel.members. Is it by design?

**Comment by leggetter** [comment]
Cleaning down issues in the hope that https://github.com/leggetter/pusher-test-stub/tree/2.0.0 resolves things.

It should be possible to get the `me` property on a presence channel.

You can also add/remove members and set the current member by ID:

```js
// A member
presenceChannel.members.addMember( {user_id: 1, user_info:{}} );
presenceChannel.members.addMember( {user_id: 2, user_info:{}} );

// set member with `user_id` of 1 as `me`
presenceChannel.members.setMyID(1);

presenceChannel.removeMember({user_id:1});
```
