### ISSUE TITLE
The future of the pusher-test-stub

### ISSUE THREAD

**Issue by leggetter** [leggetter/pusher-test-stub#11]
@dandehavilland @kjcpaas @jbescoyez After a year and a half away, I'm about to rejoin Pusher. The pusher-js library has moved on quite a bit since I wrote this test stub however there has been recent activity on this project.

How important is this project to you? Would you accept an alternative testing solution e.g. using a mock library?

It would be great to get your feedback so that I can talk to the pusher-js library authors and come up with a plan for helping you test pusher-js integration.

Also, if you have a specific testing use case that you'd like to share it would be great to pass that information on too.

Thanks.

**Comment by jherdman** [comment]
@leggetter whatever came of the discussion? It'd also be great to be able to install and manage this tool with Bower, Node, etc.

**Comment by leggetter** [comment]
@jherdman - a clear decision hasn't been made so I would like to make some updates to this library.

## Short - Medium term plan

So, the short to medium term future is to fix the short comings of this project in the most efficient way possible. That'll likely be to require pusher-js to be included and for the pusher-test-stub to override the `Pusher` constructor and use some of the utility functions in pusher-js that were previously just copied over. This _should_ significantly decrease the maintenance requirement of the project.

## EventDispatcher

By using pusher-js we get access to the `EventsDispatcher` within the library. This should fix #8 and mean we can close #12.

## Presence Support

Presence has been neglected so I'm hopeful that the stub will also be able to use some of the classes defined in pusher-js to make it easier to support this. That will hopefully resolve #1 and #4.

## Project Structure & Build

As part of this it would also make sense to:

* Pull in pusher-js from Bower
* Introduce a proper build system and have a clear place where the built version is located
* Put pusher-test-stub in Bower

## Timescales

The tricky part here is when I'm going to find time to do this. It _may_ be the sort of thing I can do in a few evenings. But I won't know until I make a start on it. Likelihood is that I won't have the time to look into this until 15th January at the earliest.

I hope this gives everybody an idea that they'll be able to rely on this project being updated in the near future. The existing pull requests may need to be closed based on the suggested new approach but after that's been plugged in additional contributes are of course very much appreciated.

Feel free to follow up with any thoughts or questions.

**Comment by jherdman** [comment]
Is there anything I can do to help with this? I'm trying to use this library on a new Ember project using Pusher 2+, and am sufficiently motivated to help in whatever way I can. I confess I'm not very familiar with Pusher itself.

**Comment by leggetter** [comment]
@jherdman I'd love some help.

The original goals from [the blog post](http://blog.pusher.com/testing-your-integration-with-the-pusher-javascript-library/) were to offer:

* A constructor – creates a stub Pusher instance
* Subscribe to channels – returns a stub channel object
* Bind to events on channels including presence events
* Bind to events on the Pusher.connection object
* Access channels created though calls to subscribe
* Trigger events on a channel including trigger presence events
* Trigger events on the connection object

But to be a full stub it really needs to offer full `Pusher` instance functionality.

The main problem we're working around with this is state-based functionality e.g. when the `Pusher` instance is connected I allow X but disallow Y. We ultimately want to be able to set up state for some tests and assert our application has behaved in a particular way. Or we want to be able to control that our instance triggers a given event on a channel so that the application logic in our code is executed and we can assert the resultant state.

The first version of this only really allowed events to be triggered. I think we could also offer a few helper functions around state control - particularly with presence.

## Public API

There's public API that pusher-js offers:

### EventsDispacher

The `EventsDispacher` is used by `Connection`, `Channel` (and all channel types). The functions on this include:

* `obj.bind( eventName, callback )` - bind to all events with an event name: 
* `obj.unbind( eventName[, callback] )` - Unbind to all events with a given name
* `obj.bind_all( callback )` - Bind to all absolutely all events. *I'd be interested if anybody uses this*
* `obj.unbind_all( callback )` - Unbind the all callback handler. *I'd be interested if anybody uses this*

### Pusher

Static variables:

* `Pusher.instances` -  List of instances of `Pusher` objects instances

Constructor:

* `new Pusher( key[, options] )` - Constructor

Functions:

* `pusher.subscribe( channelName )`
* `pusher.unsubscribe( channelName )`
* `pusher.channel( channelName )` - get a channel by name
* `pusher.allChannels()`
* `pusher.connect()`
* `pusher.disconnect()`

Ones I'm hoping we can ignore:

* `pusher.bind( eventName, callback )` - Bind to all events with an event name: 
* `pusher.bind_all( callback )` - Bind to all absolutely all events

Properties:

* `pusher.key` - The current app key: 

### Pusher.Connection

Inherits from `EventsDispacher`.

* `connection.state` - Connection state: 

### Public Channel

The basic channel type which inherits from `EventsDispacher`. It doesn't offer any other functions other than those exposed by the object it inherits from.

However, there are a few properties:

* `channel.subscribed` - Subscription state:
* `channel.name` - Channel name: 
* `channel.pusher` - The Pusher instance. *I'm not sure this is supposed to be on the public API. Does anybody use this?*

### Private Channel

Inherits from the public channel and as such inherits `EventsDispacher`.

* `channel.trigger( eventName, data )` - the ability to trigger client events on the channel.

### Presence Channel

Inherits from the private channel and as such inherits `EventsDispacher` and the private channel properties. Also offers access to some presence state variables.

* `channel.members` - Members on the channel. An instance of `Pusher.Members`

### Members

Functions:

* `members.get( memberId )` - get a member with a given ID
* `members.each( callback )` - used to iterate members

Properties:

* `members.count` - the number of members on the channel
* `members.me` - a reference to the current user on the channel

### Member

Not represented as an object anywhere, but the structure is:

* `member.id` - a unique user id
* `member.info` - application specific user information

## Test Helpers

The next thing to consider is what functions exist to help us write tests.

With events in mind the `EventsDispatcher` offers a simple way of triggering events from all channel types and the `Connection` object:

* `emit( eventName, data )`

So it'll be easy to get channels and the connection to trigger events and test our application code.

`Pusher.Members` does expose some useful functions, but they're not supposed to be public so could change. It could be that we do something with pusher-js to ensure they don't change - maybe set a conventions to make functions as *protected* - or something. Failing that we'll need to create a stub version that we're in control of.

**Please provide details of the test helper functions that you'd like to see - maybe as tests. See "A potential approach to development" below*.**

## pusher-test-stub 2

### Overview

Off the top of my head this is how we should go about creating the 2nd version of the test stub:

1. Include pusher-js
2. Include pusher-test-stub.js
3. Stub captures properties on `Pusher` definition e.g. `Pusher.Members`, `Pusher.Channel`, `Pusher.EventsDispacher` etc. so they can be used to help us with the test stub. And so that the code we use can access these things still.
4. Override the `Pusher` constructor and ensure the public API is fullfiled. Where possible use the objects already exposed by Pusher e.g. the `Pusher.EventsDispatcher`, `Pusher.Util` and `Pusher.Members` objects.	

### A potential approach to development

What may be nice is to first write a number of tests that we want to be able to perform against the `Pusher` instance. Then we can fill in the contents to get the tests to pass. I can obviously check to make sure the functionality is as-expected, write some of the code and provide guidance.

**If you have a set of tests please feel free to add each test as an issue and we can cross them off as the stub allows that to be tested**.

*How does this approach sound?*

**Comment by leggetter** [comment]
I'm guessing that I provided a bit too much detail previously, or I just made it sound too complicated :laughing:. Sorry!

I've **finally** pushed a new version of the pusher-test-stub that I'd love to get feedback on. It does everything that's detailed above in the way that's detailed above.

It's presently in a [2.0.0 branch](https://github.com/leggetter/pusher-test-stub/tree/2.0.0).

You can get it via bower:

```
bower install pusher-test-stub#2.0.0
```

And you use it by including it *after* the Pusher JS script tag:

```html
<script src="//js.pusher.com/2.2/pusher.min.js"></script>
<script src="bower_components/pusher-test-stub/dist/pusher-test-stub.js"></script>
```

I'm going to close this issue. But please raise new issues if you have any questions or ideas for improvement.
