### ISSUE TITLE
Handling multiple events on same channel

### ISSUE THREAD

**Issue by vijayj** [leggetter/pusher-test-stub#2]
I am actively using the stub in my jasmine tests and it's really good. One use case I ran into  subscribing multiple events to same channel. 

here's the code
pusher.subscribe("comment-1", 'started-typing', function() {});
pusher.subscribe("comment-1", 'stopped-typing', function() {});
pusher.subscribe("comment-1", 'delete', function() {});

The issue is that the subscribe code  in stub creates a channel on each call. A simple if condition would fix it. Here's my attempt using an if condition to see if channel is already created

```javascript
    /**
     * Subscribe to a channel.
     * @return {com.pusher.test.framework.Channel} A stub channel object.
     */
    Pusher.prototype.subscribe = function (channelName) {
        var channel = null;
        if (this._channels[channelName]) {
            channel = this._channels[channelName];
        }
        else {
            channel = new Channel(channelName);
            this._channels[channelName] = channel;
        }
        return channel;
    };
```

**Comment by leggetter** [comment]
This should be resolved by the new version:
https://github.com/leggetter/pusher-test-stub/tree/2.0.0

However, it's likely that as of the official Pusher JS 3.0 release subscribing to the same channel multiple times will result in at least a warning in the console.

The code in the original issue should instead be:

```js
var channel = pusher.subscribe("comment-1");
channel.bind('started-typing', function() {});
channel.bind('stopped-typing', function() {});
channel.bind( 'delete', function() {});
```
