### ISSUE TITLE
Adding members to channel

### ISSUE THREAD

**Issue by kjcpaas** [leggetter/pusher-test-stub#4]
If I understand correctly, it seems like the `channel.members` is not created for presence channels. This is why I'd like to at least manually create it after subscription.

I saw a Members prototype (https://github.com/leggetter/pusher-test-stub/blob/master/build/bin/pusher-test-stub.js#L280) but I don't now how to use it. Can anyone tell me how to use it?

**Comment by leggetter** [comment]
Cleaning down issues in the hope that https://github.com/leggetter/pusher-test-stub/tree/2.0.0 resolves things.
