### ISSUE TITLE
unbind_all missing from EventsDispatcher

### ISSUE THREAD

**Issue by dandehavilland** [leggetter/pusher-test-stub#8]
To keep the API in-line with the current [Pusher release](/pusher/pusher-js/blob/95d1130dd1d2f9d69a126fdfc334633277a847ff/src/events_dispatcher.js#L28), `unbind_all` should be implemented for pusher-test-stub.

**Comment by leggetter** [comment]
Cleaning down issues in the hope that https://github.com/leggetter/pusher-test-stub/tree/2.0.0 resolves things.
